DROP DATABASE IF EXISTS itil_ticketing_saas;

CREATE DATABASE itil_ticketing_saas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE itil_ticketing_saas;

CREATE TABLE tenants (
    tenant_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_code VARCHAR(50) UNIQUE NOT NULL,
    company_name VARCHAR(200) NOT NULL,
    subdomain VARCHAR(100) UNIQUE,
    custom_domain VARCHAR(200) UNIQUE,
    subscription_plan ENUM('free', 'basic', 'professional', 'enterprise', 'custom') DEFAULT 'basic',
    subscription_status ENUM('trial', 'active', 'suspended', 'cancelled', 'expired') DEFAULT 'trial',
    trial_start_date DATE,
    trial_end_date DATE,
    subscription_start_date DATE,
    subscription_end_date DATE,
    max_users INT DEFAULT 10,
    max_tickets_per_month INT DEFAULT 1000,
    max_storage_gb INT DEFAULT 10,
    features JSON,
    billing_email VARCHAR(100),
    contact_name VARCHAR(100),
    contact_email VARCHAR(100),
    contact_phone VARCHAR(20),
    address TEXT,
    country VARCHAR(100),
    timezone VARCHAR(50) DEFAULT 'UTC',
    language VARCHAR(10) DEFAULT 'es',
    currency VARCHAR(3) DEFAULT 'EUR',
    logo_url VARCHAR(500),
    custom_branding JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    INDEX idx_subdomain (subdomain),
    INDEX idx_status (subscription_status),
    INDEX idx_active (is_active)
);

CREATE TABLE tenant_settings (
    setting_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    setting_type ENUM('string', 'number', 'boolean', 'json') DEFAULT 'string',
    description TEXT,
    updated_by INT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    UNIQUE KEY unique_tenant_setting (tenant_id, setting_key),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE tenant_usage (
    usage_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    usage_month DATE NOT NULL,
    users_count INT DEFAULT 0,
    tickets_created INT DEFAULT 0,
    storage_used_gb DECIMAL(10,2) DEFAULT 0,
    api_calls INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    UNIQUE KEY unique_tenant_month (tenant_id, usage_month),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    department_id INT,
    role ENUM('end_user', 'technician', 'manager', 'admin', 'tenant_admin') DEFAULT 'end_user',
    is_active BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMP NULL,
    password_changed_at TIMESTAMP NULL,
    failed_login_attempts INT DEFAULT 0,
    locked_until TIMESTAMP NULL,
    must_change_password BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    UNIQUE KEY unique_tenant_username (tenant_id, username),
    UNIQUE KEY unique_tenant_email (tenant_id, email),
    INDEX idx_tenant (tenant_id),
    INDEX idx_email (email),
    INDEX idx_department (department_id),
    INDEX idx_active (tenant_id, is_active)
);

CREATE TABLE departments (
    department_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    department_code VARCHAR(20) NOT NULL,
    manager_id INT,
    location VARCHAR(100),
    cost_center VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    UNIQUE KEY unique_tenant_dept_code (tenant_id, department_code),
    INDEX idx_tenant (tenant_id),
    INDEX idx_manager (manager_id)
);

CREATE TABLE teams (
    team_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    team_name VARCHAR(100) NOT NULL,
    team_type ENUM('support', 'development', 'infrastructure', 'security', 'network') NOT NULL,
    team_lead_id INT,
    department_id INT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (team_lead_id) REFERENCES users(user_id),
    FOREIGN KEY (department_id) REFERENCES departments(department_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_team_type (team_type)
);

CREATE TABLE team_members (
    team_member_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    team_id INT NOT NULL,
    user_id INT NOT NULL,
    role_in_team ENUM('member', 'lead', 'backup') DEFAULT 'member',
    joined_date DATE NOT NULL,
    left_date DATE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES teams(team_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    UNIQUE KEY unique_active_member (tenant_id, team_id, user_id, left_date),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE ci_types (
    ci_type_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NULL,
    type_name VARCHAR(50) NOT NULL,
    type_category ENUM('hardware', 'software', 'network', 'database', 'service', 'documentation') NOT NULL,
    description TEXT,
    is_custom BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tenant (tenant_id),
    UNIQUE KEY unique_type_name (tenant_id, type_name)
);

CREATE TABLE configuration_items (
    ci_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ci_number VARCHAR(50) NOT NULL,
    ci_name VARCHAR(100) NOT NULL,
    ci_type_id INT NOT NULL,
    status ENUM('active', 'inactive', 'retired', 'under_maintenance', 'planned') DEFAULT 'active',
    owner_id INT,
    managed_by_team_id INT,
    location VARCHAR(100),
    serial_number VARCHAR(100),
    asset_tag VARCHAR(50),
    manufacturer VARCHAR(100),
    model VARCHAR(100),
    purchase_date DATE,
    warranty_expiry DATE,
    cost DECIMAL(10,2),
    ip_address VARCHAR(45),
    hostname VARCHAR(100),
    operating_system VARCHAR(100),
    version VARCHAR(50),
    description TEXT,
    criticality ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (ci_type_id) REFERENCES ci_types(ci_type_id),
    FOREIGN KEY (owner_id) REFERENCES users(user_id),
    FOREIGN KEY (managed_by_team_id) REFERENCES teams(team_id),
    UNIQUE KEY unique_tenant_ci_number (tenant_id, ci_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_ci_type (ci_type_id),
    INDEX idx_criticality (criticality)
);

CREATE TABLE ci_relationships (
    relationship_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    parent_ci_id INT NOT NULL,
    child_ci_id INT NOT NULL,
    relationship_type ENUM('depends_on', 'part_of', 'connected_to', 'uses', 'hosted_on', 'runs_on') NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (parent_ci_id) REFERENCES configuration_items(ci_id) ON DELETE CASCADE,
    FOREIGN KEY (child_ci_id) REFERENCES configuration_items(ci_id) ON DELETE CASCADE,
    INDEX idx_tenant (tenant_id),
    INDEX idx_parent (parent_ci_id),
    INDEX idx_child (child_ci_id)
);

CREATE TABLE categories (
    category_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NULL,
    category_name VARCHAR(100) NOT NULL,
    parent_category_id INT,
    category_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    is_custom BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (parent_category_id) REFERENCES categories(category_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_category_type (category_type),
    INDEX idx_parent (parent_category_id),
    UNIQUE KEY unique_category_name (tenant_id, category_name, category_type)
);

CREATE TABLE priority_matrix (
    priority_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NULL,
    priority_name VARCHAR(20) NOT NULL,
    priority_level INT NOT NULL,
    impact ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    urgency ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    response_time_hours INT NOT NULL,
    resolution_time_hours INT NOT NULL,
    description TEXT,
    is_custom BOOLEAN DEFAULT FALSE,
    INDEX idx_tenant (tenant_id),
    UNIQUE KEY unique_impact_urgency (tenant_id, impact, urgency)
);

CREATE TABLE incidents (
    incident_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    incident_number VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    reported_by INT NOT NULL,
    reported_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id INT,
    subcategory_id INT,
    affected_ci_id INT,
    impact ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    urgency ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    priority_id INT,
    status ENUM('new', 'assigned', 'in_progress', 'on_hold', 'resolved', 'closed', 'cancelled') DEFAULT 'new',
    assigned_to INT,
    assigned_team_id INT,
    resolution_code VARCHAR(100),
    resolution_notes TEXT,
    workaround TEXT,
    related_problem_id INT,
    related_change_id INT,
    escalation_level INT DEFAULT 0,
    reopened_count INT DEFAULT 0,
    sla_breach BOOLEAN DEFAULT FALSE,
    target_resolution_date TIMESTAMP NULL,
    resolved_date TIMESTAMP NULL,
    closed_date TIMESTAMP NULL,
    closed_by INT,
    closure_category VARCHAR(100),
    customer_satisfaction_rating INT CHECK (customer_satisfaction_rating BETWEEN 1 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (reported_by) REFERENCES users(user_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (affected_ci_id) REFERENCES configuration_items(ci_id),
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    FOREIGN KEY (assigned_to) REFERENCES users(user_id),
    FOREIGN KEY (assigned_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (closed_by) REFERENCES users(user_id),
    UNIQUE KEY unique_tenant_incident_number (tenant_id, incident_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_priority (priority_id),
    INDEX idx_assigned (assigned_to),
    INDEX idx_reported_date (tenant_id, reported_date),
    INDEX idx_sla_breach (tenant_id, sla_breach)
);

CREATE TABLE problems (
    problem_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    problem_number VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    identified_by INT NOT NULL,
    identified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id INT,
    subcategory_id INT,
    affected_ci_id INT,
    impact ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    urgency ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    priority_id INT,
    status ENUM('new', 'investigation', 'known_error', 'resolved', 'closed', 'cancelled') DEFAULT 'new',
    assigned_to INT,
    assigned_team_id INT,
    root_cause TEXT,
    root_cause_category VARCHAR(100),
    workaround TEXT,
    permanent_solution TEXT,
    resolution_date TIMESTAMP NULL,
    closed_date TIMESTAMP NULL,
    closed_by INT,
    related_change_id INT,
    known_error_date TIMESTAMP NULL,
    kedb_entry_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (identified_by) REFERENCES users(user_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (affected_ci_id) REFERENCES configuration_items(ci_id),
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    FOREIGN KEY (assigned_to) REFERENCES users(user_id),
    FOREIGN KEY (assigned_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (closed_by) REFERENCES users(user_id),
    UNIQUE KEY unique_tenant_problem_number (tenant_id, problem_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_priority (priority_id),
    INDEX idx_assigned (assigned_to)
);

CREATE TABLE known_errors (
    kedb_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    kedb_number VARCHAR(50) NOT NULL,
    problem_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    error_description TEXT NOT NULL,
    symptoms TEXT NOT NULL,
    root_cause TEXT NOT NULL,
    workaround TEXT,
    permanent_solution TEXT,
    affected_cis TEXT,
    occurrence_frequency ENUM('rare', 'occasional', 'frequent', 'very_frequent') DEFAULT 'occasional',
    severity ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    status ENUM('active', 'resolved', 'archived') DEFAULT 'active',
    created_by INT NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    resolution_date TIMESTAMP NULL,
    times_referenced INT DEFAULT 0,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id) REFERENCES problems(problem_id),
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    UNIQUE KEY unique_tenant_kedb_number (tenant_id, kedb_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_severity (severity),
    FULLTEXT idx_search (title, error_description, symptoms)
);

CREATE TABLE incident_problem_relations (
    relation_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    incident_id INT NOT NULL,
    problem_id INT NOT NULL,
    relationship_type ENUM('caused_by', 'related_to', 'duplicate_of') NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (incident_id) REFERENCES incidents(incident_id) ON DELETE CASCADE,
    FOREIGN KEY (problem_id) REFERENCES problems(problem_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    UNIQUE KEY unique_incident_problem (tenant_id, incident_id, problem_id),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE change_types (
    change_type_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NULL,
    type_name VARCHAR(50) NOT NULL,
    description TEXT,
    requires_cab_approval BOOLEAN DEFAULT TRUE,
    standard_change BOOLEAN DEFAULT FALSE,
    is_custom BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tenant (tenant_id),
    UNIQUE KEY unique_type_name (tenant_id, type_name)
);

CREATE TABLE changes (
    change_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    change_number VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    change_type_id INT NOT NULL,
    requested_by INT NOT NULL,
    requested_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id INT,
    affected_ci_id INT,
    impact ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    urgency ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    priority_id INT,
    risk_level ENUM('low', 'medium', 'high', 'critical') NOT NULL,
    status ENUM('draft', 'submitted', 'under_review', 'approved', 'scheduled', 'in_progress', 'implemented', 'completed', 'rejected', 'cancelled', 'failed', 'rolled_back') DEFAULT 'draft',
    assigned_to INT,
    assigned_team_id INT,
    reason_for_change TEXT NOT NULL,
    implementation_plan TEXT,
    backout_plan TEXT NOT NULL,
    test_plan TEXT,
    business_justification TEXT,
    related_problem_id INT,
    related_incident_id INT,
    scheduled_start_date TIMESTAMP NULL,
    scheduled_end_date TIMESTAMP NULL,
    actual_start_date TIMESTAMP NULL,
    actual_end_date TIMESTAMP NULL,
    requires_downtime BOOLEAN DEFAULT FALSE,
    downtime_duration_minutes INT,
    cab_approval_required BOOLEAN DEFAULT TRUE,
    cab_review_date TIMESTAMP NULL,
    approved_by INT,
    approval_date TIMESTAMP NULL,
    rejection_reason TEXT,
    implementation_notes TEXT,
    post_implementation_review TEXT,
    success BOOLEAN,
    closed_date TIMESTAMP NULL,
    closed_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (change_type_id) REFERENCES change_types(change_type_id),
    FOREIGN KEY (requested_by) REFERENCES users(user_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (affected_ci_id) REFERENCES configuration_items(ci_id),
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    FOREIGN KEY (assigned_to) REFERENCES users(user_id),
    FOREIGN KEY (assigned_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (related_problem_id) REFERENCES problems(problem_id),
    FOREIGN KEY (approved_by) REFERENCES users(user_id),
    FOREIGN KEY (closed_by) REFERENCES users(user_id),
    UNIQUE KEY unique_tenant_change_number (tenant_id, change_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_risk (risk_level),
    INDEX idx_scheduled_dates (scheduled_start_date, scheduled_end_date)
);

CREATE TABLE cab_members (
    cab_member_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    user_id INT NOT NULL,
    role VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    appointed_date DATE NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (tenant_id, is_active)
);

CREATE TABLE change_approvals (
    approval_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    change_id INT NOT NULL,
    approver_id INT NOT NULL,
    approval_status ENUM('pending', 'approved', 'rejected', 'abstained') DEFAULT 'pending',
    comments TEXT,
    approval_date TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (change_id) REFERENCES changes(change_id) ON DELETE CASCADE,
    FOREIGN KEY (approver_id) REFERENCES users(user_id),
    UNIQUE KEY unique_change_approver (tenant_id, change_id, approver_id),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE change_affected_cis (
    affected_ci_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    change_id INT NOT NULL,
    ci_id INT NOT NULL,
    impact_description TEXT,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (change_id) REFERENCES changes(change_id) ON DELETE CASCADE,
    FOREIGN KEY (ci_id) REFERENCES configuration_items(ci_id),
    UNIQUE KEY unique_change_ci (tenant_id, change_id, ci_id),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE service_catalog (
    service_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    service_name VARCHAR(100) NOT NULL,
    service_code VARCHAR(50) NOT NULL,
    description TEXT,
    category_id INT,
    service_owner_id INT,
    support_team_id INT,
    estimated_completion_hours INT,
    requires_approval BOOLEAN DEFAULT FALSE,
    approval_workflow TEXT,
    cost DECIMAL(10,2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (service_owner_id) REFERENCES users(user_id),
    FOREIGN KEY (support_team_id) REFERENCES teams(team_id),
    UNIQUE KEY unique_tenant_service_code (tenant_id, service_code),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (tenant_id, is_active)
);

CREATE TABLE service_requests (
    request_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    request_number VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    service_id INT,
    requested_by INT NOT NULL,
    requested_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    category_id INT,
    impact ENUM('low', 'medium', 'high', 'critical') DEFAULT 'low',
    urgency ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    priority_id INT,
    status ENUM('draft', 'submitted', 'pending_approval', 'approved', 'rejected', 'assigned', 'in_progress', 'on_hold', 'completed', 'cancelled', 'closed') DEFAULT 'submitted',
    assigned_to INT,
    assigned_team_id INT,
    approval_required BOOLEAN DEFAULT FALSE,
    approved_by INT,
    approval_date TIMESTAMP NULL,
    rejection_reason TEXT,
    justification TEXT,
    estimated_cost DECIMAL(10,2),
    actual_cost DECIMAL(10,2),
    target_completion_date TIMESTAMP NULL,
    completed_date TIMESTAMP NULL,
    closed_date TIMESTAMP NULL,
    closed_by INT,
    customer_satisfaction_rating INT CHECK (customer_satisfaction_rating BETWEEN 1 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (service_id) REFERENCES service_catalog(service_id),
    FOREIGN KEY (requested_by) REFERENCES users(user_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    FOREIGN KEY (assigned_to) REFERENCES users(user_id),
    FOREIGN KEY (assigned_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (approved_by) REFERENCES users(user_id),
    FOREIGN KEY (closed_by) REFERENCES users(user_id),
    UNIQUE KEY unique_tenant_request_number (tenant_id, request_number),
    INDEX idx_tenant (tenant_id),
    INDEX idx_status (tenant_id, status),
    INDEX idx_service (service_id),
    INDEX idx_requested_date (tenant_id, requested_date)
);

CREATE TABLE comments (
    comment_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    ticket_id INT NOT NULL,
    comment_text TEXT NOT NULL,
    is_internal BOOLEAN DEFAULT FALSE,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id),
    INDEX idx_created_at (created_at)
);

CREATE TABLE work_notes (
    work_note_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    ticket_id INT NOT NULL,
    work_note_text TEXT NOT NULL,
    hours_worked DECIMAL(5,2),
    work_type VARCHAR(100),
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id)
);

CREATE TABLE attachments (
    attachment_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request', 'ci') NOT NULL,
    ticket_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(50),
    file_size_kb INT,
    uploaded_by INT NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id)
);

CREATE TABLE sla_definitions (
    sla_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    sla_name VARCHAR(100) NOT NULL,
    sla_type ENUM('incident', 'service_request', 'change') NOT NULL,
    priority_id INT NOT NULL,
    response_time_hours INT NOT NULL,
    resolution_time_hours INT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_type_priority (tenant_id, sla_type, priority_id)
);

CREATE TABLE sla_tracking (
    sla_tracking_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    ticket_id INT NOT NULL,
    sla_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    response_due_time TIMESTAMP NULL,
    resolution_due_time TIMESTAMP NULL,
    response_time TIMESTAMP NULL,
    resolution_time TIMESTAMP NULL,
    response_breached BOOLEAN DEFAULT FALSE,
    resolution_breached BOOLEAN DEFAULT FALSE,
    paused_duration_minutes INT DEFAULT 0,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (sla_id) REFERENCES sla_definitions(sla_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id),
    INDEX idx_breach (tenant_id, response_breached, resolution_breached)
);

CREATE TABLE escalation_rules (
    escalation_rule_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    priority_id INT,
    trigger_condition ENUM('time_based', 'sla_breach', 'manual', 'status_change') NOT NULL,
    trigger_minutes INT,
    escalate_to_user_id INT,
    escalate_to_team_id INT,
    notification_message TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (priority_id) REFERENCES priority_matrix(priority_id),
    FOREIGN KEY (escalate_to_user_id) REFERENCES users(user_id),
    FOREIGN KEY (escalate_to_team_id) REFERENCES teams(team_id),
    INDEX idx_tenant (tenant_id)
);

CREATE TABLE escalation_history (
    escalation_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    ticket_id INT NOT NULL,
    escalation_rule_id INT,
    escalated_from_user_id INT,
    escalated_to_user_id INT,
    escalated_from_team_id INT,
    escalated_to_team_id INT,
    escalation_reason TEXT,
    escalation_level INT NOT NULL,
    escalated_by INT NOT NULL,
    escalated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (escalation_rule_id) REFERENCES escalation_rules(escalation_rule_id),
    FOREIGN KEY (escalated_from_user_id) REFERENCES users(user_id),
    FOREIGN KEY (escalated_to_user_id) REFERENCES users(user_id),
    FOREIGN KEY (escalated_from_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (escalated_to_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (escalated_by) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id)
);

CREATE TABLE notifications (
    notification_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    user_id INT NOT NULL,
    ticket_type ENUM('incident', 'problem', 'change', 'service_request') NOT NULL,
    ticket_id INT NOT NULL,
    notification_type ENUM('assignment', 'update', 'escalation', 'sla_warning', 'closure', 'approval_request') NOT NULL,
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_user_unread (tenant_id, user_id, is_read),
    INDEX idx_ticket (tenant_id, ticket_type, ticket_id)
);

CREATE TABLE audit_log (
    audit_id INT PRIMARY KEY AUTO_INCREMENT,
    tenant_id INT NOT NULL,
    table_name VARCHAR(50) NOT NULL,
    record_id INT NOT NULL,
    action ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    field_name VARCHAR(100),
    old_value TEXT,
    new_value TEXT,
    changed_by INT NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES users(user_id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_table_record (tenant_id, table_name, record_id),
    INDEX idx_changed_at (changed_at)
);

CREATE VIEW v_active_tickets_summary AS
SELECT 
    t.tenant_id,
    t.company_name,
    COUNT(DISTINCT i.incident_id) as active_incidents,
    COUNT(DISTINCT p.problem_id) as active_problems,
    COUNT(DISTINCT c.change_id) as active_changes,
    COUNT(DISTINCT sr.request_id) as active_requests
FROM tenants t
LEFT JOIN incidents i ON t.tenant_id = i.tenant_id AND i.status NOT IN ('closed', 'cancelled')
LEFT JOIN problems p ON t.tenant_id = p.tenant_id AND p.status NOT IN ('closed', 'cancelled')
LEFT JOIN changes c ON t.tenant_id = c.tenant_id AND c.status NOT IN ('completed', 'cancelled', 'rejected')
LEFT JOIN service_requests sr ON t.tenant_id = sr.tenant_id AND sr.status NOT IN ('closed', 'cancelled')
WHERE t.is_active = TRUE
GROUP BY t.tenant_id, t.company_name;
