<div class="page-header">
    <h1 class="page-title">Cambios Programados</h1>
</div>

<div class="calendar-view">
    <div class="calendar-header">
        <div class="month-year"><?php echo date('F Y'); ?></div>
        <div class="nav-buttons">
            <button class="nav-btn"><i class="fas fa-chevron-left"></i></button>
            <button class="nav-btn" title="Hoy">Hoy</button>
            <button class="nav-btn"><i class="fas fa-chevron-right"></i></button>
        </div>
    </div>

    <!-- Calendar Grid Mockup (Visual only for MVP) -->
    <div class="calendar-grid">
        <div class="day-header">Lun</div>
        <div class="day-header">Mar</div>
        <div class="day-header">Mié</div>
        <div class="day-header">Jue</div>
        <div class="day-header">Vie</div>
        <div class="day-header">Sab</div>
        <div class="day-header">Dom</div>
        <!-- Days would be generated by PHP loop here in full version -->
        <?php for($i=1; $i<=30; $i++): ?>
            <div class="day-cell">
                <div class="day-number"><?php echo $i; ?></div>
                <?php if ($i % 5 == 0): ?>
                    <div class="day-changes">
                        <div class="change-dot"></div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endfor; ?>
    </div>
</div>

<div class="changes-list" style="background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
    <div class="list-header" style="padding: 24px; border-bottom: 1px solid #e0e0e0; display: flex; justify-content: space-between; align-items: center;">
        <div class="list-title" style="font-size: 16px; font-weight: 600;">Cambios Próximos</div>
        <a href="index.php?page=create_change" class="btn-primary" style="text-decoration: none;">
            <i class="fas fa-plus"></i> Nuevo Cambio
        </a>
    </div>

    <?php if (empty($changes)): ?>
        <p style="padding: 20px; color: #666;">No hay cambios programados.</p>
    <?php else: ?>
        <?php foreach ($changes as $change): ?>
            <div class="change-item" style="display: grid; grid-template-columns: 100px 1fr 120px 120px 100px 120px; gap: 16px; padding: 16px 24px; border-bottom: 1px solid #f0f0f0; align-items: center;">
                <div class="change-id" style="font-weight: 600; color: #2180AE;"><?php echo htmlspecialchars($change['change_number']); ?></div>
                <div class="change-title" style="font-weight: 500;"><?php echo htmlspecialchars($change['title']); ?></div>
                <div class="change-type" style="font-size: 12px; font-weight: 600; text-transform: uppercase; background: #e8f4f8; color: #2180AE; padding: 4px 8px; border-radius: 4px; width: fit-content;"><?php echo htmlspecialchars($change['type_name']); ?></div>
                <div class="status-badge <?php echo ($change['status'] == 'approved') ? 'approved' : 'pending'; ?>">
                    <?php echo htmlspecialchars(ucfirst($change['status'])); ?>
                </div>
                <div class="risk-badge risk-<?php echo strtolower($change['risk_level']); ?>">
                    <?php echo htmlspecialchars(ucfirst($change['risk_level'])); ?>
                </div>
                <div class="scheduled-date" style="font-size: 12px; color: #666;"><?php echo htmlspecialchars(date('d M H:i', strtotime($change['created_at']))); ?></div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
